<?
	MenuInicio('AjWiki');
	MenuOpcionRelativa('Principal','index.php');
	MenuOpcionRelativa('Documentaci&oacute;n','index.php?page=Documentation');
	MenuOpcionRelativa('Downloads','index.php?page=Downloads');
	MenuOpcionRelativa('Licencia','index.php?page=License');
	MenuOpcionRelativa('Enlaces','index.php?page=Links');
	MenuFinal();
?>